In [1]:
import numpy as np
import tensorflow as tf

In [2]:
#  Text to Word : Split

sentence = "The brown fox is quick and he is jumping over the lazy dog"

words = sentence.split()

print(words)

['The', 'brown', 'fox', 'is', 'quick', 'and', 'he', 'is', 'jumping', 'over', 'the', 'lazy', 'dog']


In [3]:
# Length of the senetence

print(len(words))

13


In [4]:
# Max length of the word in document
np.max([len(x) for x in words])

7

In [5]:
# Vocabulary List

from keras.preprocessing.text import text_to_word_sequence

sentence = "The brown fox is quick and he is jumping over the lazy dog"

vocab = set(text_to_word_sequence(sentence))
vocab_size = len(vocab)

print("Vocabulary:",vocab)
print("Vocabulary size:",vocab_size)

Using TensorFlow backend.


Vocabulary: {'is', 'brown', 'the', 'he', 'over', 'jumping', 'lazy', 'dog', 'and', 'quick', 'fox'}
Vocabulary size: 11


In [7]:
# Text to word Sequence

from keras.preprocessing.text import text

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

[[w for w in text.text_to_word_sequence(doc)] for doc in norm_bible]


[['king', 'james', 'bible'],
 ['old', 'testament', 'king', 'james', 'bible'],
 ['first', 'book', 'moses', 'called', 'genesis'],
 ['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters'],
 ['god', 'said', 'let', 'light', 'light'],
 ['god', 'saw', 'light', 'good', 'god', 'divided', 'light', 'darkness'],
 ['god', 'called', 'light', 'day', 'darkness', 'called', 'night'],
 ['evening', 'morning', 'first', 'day']]

In [23]:
# using List comprehension

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

[[word for word in document.lower().split()] for document in norm_bible]

[['king', 'james', 'bible'],
 ['old', 'testament', 'king', 'james', 'bible'],
 ['first', 'book', 'moses', 'called', 'genesis'],
 ['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters'],
 ['god', 'said', 'let', 'light', 'light'],
 ['god', 'saw', 'light', 'good', 'god', 'divided', 'light', 'darkness'],
 ['god', 'called', 'light', 'day', 'darkness', 'called', 'night'],
 ['evening', 'morning', 'first', 'day']]

In [8]:
# Word Frequency (Word Count)

word_freq = {}

for tok in sentence.split():
    if tok in word_freq:
        word_freq[tok] +=1
    else:
        word_freq[tok] = 1

print(word_freq)

{'The': 1, 'brown': 1, 'fox': 1, 'is': 2, 'quick': 1, 'and': 1, 'he': 1, 'jumping': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1}


In [9]:
# Word Frequency (Word Count)

import collections

counter = collections.Counter(sentence.split())

print(counter)

Counter({'is': 2, 'The': 1, 'brown': 1, 'fox': 1, 'quick': 1, 'and': 1, 'he': 1, 'jumping': 1, 'over': 1, 'the': 1, 'lazy': 1, 'dog': 1})


In [10]:
# Find Most Common word
counter.most_common(8)

[('is', 2),
 ('The', 1),
 ('brown', 1),
 ('fox', 1),
 ('quick', 1),
 ('and', 1),
 ('he', 1),
 ('jumping', 1)]

In [11]:
# Word Index

corpus = sentence.split()

uniq_text = set(corpus)

text_to_int = {}

for i, c in enumerate (uniq_text):
    text_to_int.update({c: i})
    
print(text_to_int)

{'is': 0, 'brown': 1, 'The': 2, 'the': 3, 'he': 4, 'over': 5, 'jumping': 6, 'lazy': 7, 'dog': 8, 'and': 9, 'quick': 10, 'fox': 11}


In [12]:
# Unique words in Senetnce

print(set(sentence.lower().split()))

{'is', 'brown', 'the', 'he', 'over', 'jumping', 'lazy', 'dog', 'and', 'quick', 'fox'}


In [13]:
# N Gram (n =2): Bigram

words =sentence.split()

n = 2
output= []
for i in range(len(words) - n+1):
    output.append(words[i:i+n])
    
output

[['The', 'brown'],
 ['brown', 'fox'],
 ['fox', 'is'],
 ['is', 'quick'],
 ['quick', 'and'],
 ['and', 'he'],
 ['he', 'is'],
 ['is', 'jumping'],
 ['jumping', 'over'],
 ['over', 'the'],
 ['the', 'lazy'],
 ['lazy', 'dog']]

In [14]:
# N Gram (n =3): Trigram

words =sentence.split()

n = 3
output= []
for i in range(len(words) - n+1):
    output.append(words[i:i+n])
    
output

[['The', 'brown', 'fox'],
 ['brown', 'fox', 'is'],
 ['fox', 'is', 'quick'],
 ['is', 'quick', 'and'],
 ['quick', 'and', 'he'],
 ['and', 'he', 'is'],
 ['he', 'is', 'jumping'],
 ['is', 'jumping', 'over'],
 ['jumping', 'over', 'the'],
 ['over', 'the', 'lazy'],
 ['the', 'lazy', 'dog']]

In [15]:
# Text to Integer

list1 = ['Located', 'on', 'the', 'southern', 'tip', 'of', 'Lake', 'Union,', 'the', 'Hilton']

text_int ={}

for i,j in enumerate(list1):
    text_int.update({j:(i+1)})
    
text_int

{'Located': 1,
 'on': 2,
 'the': 9,
 'southern': 4,
 'tip': 5,
 'of': 6,
 'Lake': 7,
 'Union,': 8,
 'Hilton': 10}

In [16]:
# Text to Integer

from keras.preprocessing import text

norm_bible = ['king james bible',
             'old testament king james bible',
             'first book moses called genesis',
             'beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters',
             'god said let light light',
             'god saw light good god divided light darkness',
             'god called light day darkness called night',
             'evening morning first day']

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[[5, 6, 7],
 [13, 14, 5, 6, 7],
 [8, 15, 16, 3, 17],
 [18, 1, 19, 20, 9],
 [9, 21, 22, 23, 4, 10, 11, 24],
 [25, 1, 26, 10, 11, 27],
 [1, 28, 29, 2, 2],
 [1, 30, 2, 31, 1, 32, 2, 4],
 [1, 3, 2, 12, 4, 3, 33],
 [34, 35, 8, 12]]

In [19]:
# Binary One Hot Encoder for One Senetence

from sklearn.preprocessing import OneHotEncoder
from keras.preprocessing.text import Tokenizer

# Bag of Word

# One Hot Encoding

doc = "Can I eat the Pizza".lower().split()

t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(doc)

# integer encode documents
encoded_docs = t.texts_to_matrix(doc, mode='count')

encoded_docs

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [20]:
# One Hot Ending for Multiple Sentence

doc = [['can', 'i', 'eat', 'the', 'pizza'],['can', 'i', 'eat', 'the', 'pizza']]


t = Tokenizer()
# fit the tokenizer on the documents
t.fit_on_texts(doc)

# integer encode documents
encoded_docs = t.texts_to_matrix(doc, mode='count')

encoded_docs

array([[0., 1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1., 1.]])

In [21]:
# One Hot Encoding : Binary

from keras.preprocessing.text import Tokenizer

# define 5 documents

docs = ['Well done!',
        'Good work',
        'Great effort',
        'nice work',
        'Excellent!']

# create the tokenizer
t = Tokenizer()

# fit the tokenizer on the documents
t.fit_on_texts(docs)

# integer encode documents
encoded_docs = t.texts_to_matrix(docs, mode='count')

print(encoded_docs)

# Word Index

#'work': 1,
# 'well': 2,
# 'done': 3,
# 'good': 4,
# 'great': 5,
# 'effort': 6,
# 'nice': 7,
# 'excellent': 8}

[[0. 0. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [22]:
# Multi Dimenstional One Hot Encosing

from keras.utils import to_categorical

x = [[1,2,3,4,5],
     [1,4,8,4,4],
     [1,2,3,3,5]]

y = to_categorical(x, num_classes=10)

y

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.]]], dtype=float32)

In [3]:
# Decode One Hot Encoded Array

from numpy import argmax

from keras.utils import to_categorical

x = [[1,2,3,4,5],
     [1,4,8,4,4],
     [1,2,3,3,5]]

print("input Array")
print(x)

print("\n")

one_hot_arry = to_categorical(x, num_classes=10)

print("One Hot Encoding of input:")
print(one_hot_arry)

print("\n")
print("Decoded output of One Hot Encoding")
decoded_one_hot = [[argmax(aa) for aa in array] for array in one_hot_arry]

print(decoded_one_hot)

input Array
[[1, 2, 3, 4, 5], [1, 4, 8, 4, 4], [1, 2, 3, 3, 5]]


One Hot Encoding of input:
[[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]]


Decoded output of One Hot Encoding
[[1, 2, 3, 4, 5], [1, 4, 8, 4, 4], [1, 2, 3, 3, 5]]


In [29]:
# Conversion of Dimention of data : specially for LSTM

# Ex : list to array of (6,) to (1,1,6)

import numpy as np

one_hot1 = [[0,0,0,1,0,0],
           [0,0,0,1,0,1],
           [0,1,0,1,0,0]]# This is List of list type

one_hot2 = [[0,0,0,1,0,0],
           [0,0,0,1,0,1],
           [0,1,0,1,0,0]]# This is List of list type

# convert to format it can be used in the LSTM input

liss = [one_hot1,one_hot2]

np.asarray(liss).shape

(2, 3, 6)

In [30]:
# embedding of the Characters in the string : for LSTM

import numpy as np

word_vec_length = 10 # maximum length of the name

char_to_int = {'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7, 
               'i': 8, 'j': 9, 'k': 10, 'l': 11, 'm': 12, 'n': 13, 'o': 14, 
               'p': 15, 'q': 16, 'r': 17, 's': 18, 't': 19, 'u': 20, 'v': 21, 
               'w': 22, 'x': 23, 'y': 24, 'z': 25, 'ö': 26, 'ä': 27, 'ü': 28,
               '-': 29, 'ß': 30, ' ': 31}

char_vec_length = len(char_to_int)


# Returns a list of n lists with n = word_vec_length
def name_encoding(name):

    # Encode input data to int, e.g. a->1, z->26
    integer_encoded = [char_to_int[char] for i, char in enumerate(name) if i < word_vec_length]
    
    # Start one-hot-encoding
    onehot_encoded = list()
    
    for value in integer_encoded:
        # create a list of n zeros, where n is equal to the number of accepted characters
        letter = [0 for _ in range(char_vec_length)]
        letter[value] = 1
        onehot_encoded.append(letter)
        
    # Fill up list to the max length. Lists need do have equal length to be able to convert it into an array
    for _ in range(word_vec_length - len(name)):
        onehot_encoded.append([0 for _ in range(char_vec_length)])
        
    return onehot_encoded

names = ['santhosh','anand','sachin','prashanth']

# use asarray to use change the shape of the array which suits for LSTM
enc = np.asarray([np.asarray(name_encoding(name)) for name in names])

print(enc.shape)

enc

(4, 10, 32)


array([[[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 1, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]])

In [2]:
names = ["santhosh","kumar","anand","joshi"] # Samples

import string
import numpy as np

# get the alphabest
string.ascii_lowercase

# List of Vocabulary
vocabs_ = [x for x in string.ascii_lowercase] # Features

# vocabulary length
vocab_length = len(string.ascii_lowercase)

# Max Sequence Length
max_seq_length = max([len(x) for x in names])

char_2_int = {} 
int_2_char = {}

# Char to Interger 
char_2_int = dict([(x,i) for i,x in enumerate(vocabs_)])

# Integer to Char
int_2_char = dict([(i,x) for i,x in enumerate(vocabs_)])

# Create Zero array for encoding

encoding = np.zeros((len(names),max_seq_length,vocab_length))

print(encoding.shape)  # (4 Samples,max length of samples,vocabulary Length

# Update the encoder matrix for the samples

for i,name in enumerate(names): # i = index value and i = sample and j =time step
    for j,char in enumerate(name):
        encoding[i,j,char_2_int[char]] = 1.0
        
encoding

(4, 8, 26)


array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0

In [23]:
from sklearn.preprocessing import LabelEncoder

doc =  ['S','C','Q','S','C','Q','S','C','Q','Q','C','Q','C','Q','Q']

label_encoder = LabelEncoder()

label_encoder.fit(['S','C','Q'])

label_encoder.transform(doc)

array([2, 0, 1, 2, 0, 1, 2, 0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [24]:
# OrdinalEncoder converts each string value to a whole number. 
# The first unique value in your column becomes 1, the second becomes 2, the third becomes 3, and so on.

from sklearn.preprocessing import OrdinalEncoder
import numpy as np

doc =  [['S'],['C'],['Q'],['S'],['C'],['Q'],['S'],['C'],['Q'],['Q'],['C'],['Q'],['C'],['Q'],['Q']]

encoder = OrdinalEncoder()

encoder.fit_transform(doc)

array([[2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.]])

In [25]:
# OrdinalEncoder

import numpy as np

X = np.array([["good", "london"],
             ["good", "tokyo"],
             ["bad", "paris"],
             ["average", "so so"],
             ["good", "tokyo"]])

encoder = OrdinalEncoder()
encoder.fit_transform(X)


array([[2., 0.],
       [2., 3.],
       [1., 1.],
       [0., 2.],
       [2., 3.]])

In [26]:
# Count Vectorizer

from sklearn.feature_extraction.text import CountVectorizer

docs = np.array(['The sun is shining',
                 'The weather is sweet',
                 'The sun is shining and the weather is sweet'])

count = CountVectorizer()
bag = count.fit_transform(docs)

bag.toarray()

# Index

# and = 0
# is =1
# shining = 2
# sun =3
# sweet =4
# the =5
# wether =6

array([[0, 1, 1, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 1, 1],
       [1, 2, 1, 1, 1, 2, 1]], dtype=int64)

In [27]:
# TFIDF

# tf-idf = tf(i,d) * idf(t,d)

# td(i,d) = term frequency

# idf(t,d) = 	log(n/1+df(t,d)) :  inverse document frequency  df(t,d) : no. of documents d that contain the term t

import pandas as pd

corpus = ["Data Science is an overlap between Arts and Science",
          "Generally,Arts graduates are right-brained and Science graduates are left-brained",
          "Excelling in both Arts and Science at a time becomes difficult",
          "Natural Language Processing is a part of Data Science"]

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_model = TfidfVectorizer()
features = tfidf_model.fit_transform(corpus)
df = pd.DataFrame(features.todense(),columns= sorted(tfidf_model.vocabulary_))

df

an       and       are      arts        at   becomes   between  \
0  0.403328  0.257439  0.000000  0.257439  0.000000  0.000000  0.403328   
1  0.000000  0.159139  0.498644  0.159139  0.000000  0.000000  0.000000   
2  0.000000  0.224449  0.000000  0.224449  0.351643  0.351643  0.000000   
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

       both   brained      data  ...  language      left   natural        of  \
0  0.000000  0.000000  0.317989  ...  0.000000  0.000000  0.000000  0.000000   
1  0.000000  0.498644  0.000000  ...  0.000000  0.249322  0.000000  0.000000   
2  0.351643  0.000000  0.000000  ...  0.000000  0.000000  0.000000  0.000000   
3  0.000000  0.000000  0.308872  ...  0.391765  0.000000  0.391765  0.391765   

    overlap      part  processing     right   science      time  
0  0.403328  0.000000    0.000000  0.000000  0.420947  0.000000  
1  0.000000  0.000000    0.000000  0.249322  0.130107  0.000000  
2  0.000000  0.000000    0.000000  0.000000  0.183502  0.351643  
3  0.000000  0.391765    0.391765  0.000000  0.204439  0.000000  

[4 rows x 26 columns]

In [12]:
# tf Idf
import pandas as pd

data = pd.read_csv("C:\MyWork\MyLearning\Career Growth\ML\Files\DataSet\Consumer Complaint.csv")

data = data[['Product','Issue']]

# Remove the null Values
data = data.dropna(subset=['Issue'])

data['category_id'] = data['Product'].factorize()[0]

In [14]:
data.head()

Product                                     Issue  category_id
0  Debt collection                     Communication tactics            0
1  Debt collection     Cont'd attempts collect debt not owed            0
2         Mortgage  Application, originator, mortgage broker            1
3      Credit card                                     Other            2
4  Debt collection     Cont'd attempts collect debt not owed            0

In [16]:
category_id_df = data[['Product', 'category_id']].drop_duplicates().sort_values('category_id')

category_id_df

Product  category_id
0             Debt collection            0
2                    Mortgage            1
3                 Credit card            2
6               Consumer loan            3
11    Bank account or service            4
13                Payday loan            5
26           Credit reporting            6
39            Money transfers            7
103              Student loan            8
730              Prepaid card            9
1134  Other financial service           10

In [18]:
category_to_id = dict(category_id_df.values)

id_to_category = dict(category_id_df[['category_id', 'Product']].values)

id_to_category

{0: 'Debt collection',
 1: 'Mortgage',
 2: 'Credit card',
 3: 'Consumer loan',
 4: 'Bank account or service',
 5: 'Payday loan',
 6: 'Credit reporting',
 7: 'Money transfers',
 8: 'Student loan',
 9: 'Prepaid card',
 10: 'Other financial service'}

In [19]:
from sklearn.feature_extraction.text import TfidfVectorizer


# sublinear_df is set to True to use a logarithmic form for frequency.

# min_df is the minimum numbers of documents a word must be present in to be kept

# norm is set to l2, to ensure all our feature vectors have a euclidian norm of 1.

# ngram_range is set to (1, 2) to indicate that we want to consider both unigrams and bigrams.

# stop_words is set to "english" to remove all common pronouns ("a", "the", ...) to reduce the number of noisy features.

tfidf = TfidfVectorizer(sublinear_tf=True, min_df=5, norm='l2', encoding='latin-1', ngram_range=(1, 2), stop_words='english')

features = tfidf.fit_transform(data.Issue).toarray()

labels = data.Product

features.shape

(28154, 304)

In [20]:
from sklearn.feature_selection import chi2
import numpy as np

N = 2

for Product, category_id in sorted(category_to_id.items()):
    features_chi2 = chi2(features, labels == category_id)
    indices = np.argsort(features_chi2[0])
    feature_names = np.array(tfidf.get_feature_names())[indices]
    
    unigrams = [v for v in feature_names if len(v.split(' ')) == 1]
    bigrams = [v for v in feature_names if len(v.split(' ')) == 2]
    
    print("# '{}':".format(Product))
    print("  . Most correlated unigrams:\n. {}".format('\n. '.join(unigrams[-N:])))
    print("  . Most correlated bigrams:\n. {}".format('\n. '.join(bigrams[-N:])))

# 'Bank account or service':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Consumer loan':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Credit card':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Credit reporting':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Debt collection':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Money transfers':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Mortgage':
  . Most correlated unigrams:
. decision
. deposits
  . Most correlated bigrams:
. debt protection
. wrong day
# 'Other financial service':
  . Most correlated unigrams:
. decision
. deposits

In [28]:
# Sequence from List

In [29]:
# Pad Sequence (Pre)

from tensorflow.keras.preprocessing.sequence import pad_sequences

raw_inputs = [[83, 91, 1, 645, 1253, 927],
              [73, 8, 3215, 55, 927],
              [711, 632, 71]]

padded_inputs = pad_sequences(raw_inputs,padding='pre')

padded_inputs

array([[  83,   91,    1,  645, 1253,  927],
       [   0,   73,    8, 3215,   55,  927],
       [   0,    0,    0,  711,  632,   71]])

In [30]:
# Pad Sequence (Post)

raw_inputs = [[83, 91, 1, 645, 1253, 927],
              [73, 8, 3215, 55, 927],
              [711, 632, 71]]

padded_inputs = pad_sequences(raw_inputs,padding='post')

padded_inputs

array([[  83,   91,    1,  645, 1253,  927],
       [  73,    8, 3215,   55,  927,    0],
       [ 711,  632,   71,    0,    0,    0]])

In [31]:
a = [[24],
     [24, 34],
     [24, 34, 1],
     [24, 34, 1, 9],
     [24, 34, 1, 9, 56],
     [24, 34, 1, 9, 56, 76],
     [24, 34, 1, 9, 56, 76, 90],
     [24, 34, 1, 9, 56, 76, 90, 11],
     [24, 34, 1, 9, 56, 76, 90, 11, 67],
     [24, 34, 1, 9, 56, 76, 90, 11, 67, 54],
     [24, 34, 1, 9, 56, 76, 90, 11, 67, 54, 14]]

import numpy as np
np.max([len(x) for x in a])

row = 11
column = len(a)

tensor = np.zeros((row,column))

for i in range(len(a)):
    lst = a[i]
    for j in range(len(lst)):
        tensor[i][j] = lst[j]

In [32]:
# N Gram from Sequence List

lst = [24,34,1,9,56,76,90,11,67,54,14]

data = []

for i in range(0,len(lst)):
    print(lst[:i+1])
    data.append(lst[:i+1])

# Padding
pad_sequences(data,padding='post')

[24]
[24, 34]
[24, 34, 1]
[24, 34, 1, 9]
[24, 34, 1, 9, 56]
[24, 34, 1, 9, 56, 76]
[24, 34, 1, 9, 56, 76, 90]
[24, 34, 1, 9, 56, 76, 90, 11]
[24, 34, 1, 9, 56, 76, 90, 11, 67]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54]
[24, 34, 1, 9, 56, 76, 90, 11, 67, 54, 14]


array([[24,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  0,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9,  0,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56,  0,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76,  0,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90,  0,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11,  0,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67,  0,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54,  0],
       [24, 34,  1,  9, 56, 76, 90, 11, 67, 54, 14]])

In [33]:
# Truncating Sequence (Pre)

import numpy as np
from tensorflow.keras.preprocessing.sequence import pad_sequences

data_vec = [['3', '18', '9', '3', '11', '5', '20'],
            ['3', '8', '1', '12'],
            ['18', '1', '8', '1'],
            ['8', '1', '9', '14'],
            ['25', '1', '8', '1'],
            ['9','3']]

# truncate sequence
truncated= pad_sequences(data_vec, maxlen=2)
print(truncated)

[[ 5 20]
 [ 1 12]
 [ 8  1]
 [ 9 14]
 [ 8  1]
 [ 9  3]]


In [34]:
# Truncating Sequence (Post)

# truncate sequence
truncated= pad_sequences(data_vec, maxlen=2,truncating='post')
print(truncated)

[[ 3 18]
 [ 3  8]
 [18  1]
 [ 8  1]
 [25  1]
 [ 9  3]]


In [35]:
# Frequency Distribution

In [36]:
# Union

document1 = ['Hi', 'How','are','You', 'I','am']
document2 = ['Hello','I','am','fine','How','about','You']

#Union : words from two documents
print("Union",set(document1) | set(document2))

Union {'are', 'You', 'Hello', 'about', 'Hi', 'am', 'fine', 'How', 'I'}


In [37]:
# Intersection

document1 = ['Hi', 'How','are','You', 'I','am']
document2 = ['Hello','I','am','fine','How','about','You']

#Intersection : common words across two documents
print("Intersection:",set(document1) & set(document2))       
            

Intersection: {'You', 'am', 'How', 'I'}


In [38]:
# Sequence to Matrix (mode = binary and num_words = 10)

from keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='binary')

x_train

array([[0., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0.]])

In [39]:
# Sequences to Matrix (mode = count and num_words = 10)
tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='count')

x_train

array([[0., 2., 1., 1., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 1., 1., 0.]])

In [40]:
# Sequences to Matrix (mode = freq and num_words = 10)
tokenizer = Tokenizer(num_words=10)

x_train = [[1,2,3,4,1],
           [4,5,],
           [6,7,8]]

x_train = tokenizer.sequences_to_matrix(x_train, mode='freq')

import pandas as pd

pd.DataFrame(x_train)

0    1    2    3    4    5         6         7         8    9
0  0.0  0.4  0.2  0.2  0.2  0.0  0.000000  0.000000  0.000000  0.0
1  0.0  0.0  0.0  0.0  0.5  0.5  0.000000  0.000000  0.000000  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0  0.333333  0.333333  0.333333  0.0

In [46]:
import string

all_letters = string.ascii_letters + ".,;''"

print("all_letters = {0}".format(all_letters))

n_letters = len(all_letters)

all_letters = abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.,;''


In [47]:
# Genrate Input for the RNN
import numpy as np

def name_intensor(name):
    name_in_tensor = np.zeros((len(name),1,n_letters))
    
    for i,letter in enumerate(name):
        name_in_tensor[i][0][all_letters.find(letter)] = 1
    
    return name_in_tensor

In [48]:
print(name_intensor('a'))
print(name_intensor('a').shape)

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(1, 1, 57)


In [49]:
print(name_intensor('af'))
print(name_intensor('af').shape)

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(2, 1, 57)


In [50]:
print(name_intensor('anand'))
print(name_intensor('anand').shape)

[[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
   0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]]
(5, 1, 57)


In [11]:
from nltk.translate.api import AlignedSent

algnsent = AlignedSent(['klein', 'ist', 'das', 'Haus'], ['the', 'house', 'is', 'small'])

print(algnsent.words)

print(algnsent.mots)

algnsent.alignment

['klein', 'ist', 'das', 'Haus']
['the', 'house', 'is', 'small']


Alignment([])

In [22]:
# Lexical translation model that ignores word orde
# It is Used for Machine Translation


import pandas as pd
from nltk.translate.ibm1 import IBMModel1
from nltk.translate.api import AlignedSent

bitext = []

bitext.append(AlignedSent(['klein', 'ist', 'das', 'haus'], ['the', 'house', 'is', 'small']))

bitext.append(AlignedSent(['das', 'haus', 'ist', 'ja', 'groß'], ['the', 'house', 'is', 'big']))

bitext.append(AlignedSent(['das', 'buch', 'ist', 'ja', 'klein'], ['the', 'book', 'is', 'small']))

bitext.append(AlignedSent(['das', 'haus'], ['the', 'house']))

bitext.append(AlignedSent(['das', 'buch'], ['the', 'book']))

bitext.append(AlignedSent(['ein', 'buch'], ['a', 'book']))

ibm1 = IBMModel1(bitext, 5)

print(ibm1.translation_table['buch']['book'])

print(ibm1.translation_table['das']['book'])

print(ibm1.translation_table['buch'][None])

print(ibm1.translation_table['ja'][None])

test_sentence = bitext[2]

print(test_sentence.words)

print(test_sentence.mots)

test_sentence.alignment

0.8890388023094323
0.061668228784061314
0.11318685275683199
0.07278526278031176
['das', 'buch', 'ist', 'ja', 'klein']
['the', 'book', 'is', 'small']


Alignment([(0, 0), (1, 1), (2, 2), (3, 2), (4, 3)])

In [52]:
# CBOW

from keras.preprocessing import text

norm_bible = ['beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters']

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

wids = [[w for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters']]

In [53]:
from keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)
word2id = tokenizer.word_index

word2id

# build vocabulary of unique words

word2id['PAD'] = 0
id2word = {v:k for k, v in word2id.items()}
wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]

wids

[[5, 1, 6, 7, 2], [2, 8, 9, 10, 11, 3, 4, 12], [13, 1, 14, 3, 4, 15]]

In [60]:
vocab_size = len(word2id)
embed_size = 100
window_size = 2 # context window size

vocab_size

16

In [61]:
window_size = 2

for words in wids:
    print(words)
    sentence_length = len(words)
    for index,word in enumerate(words):
        print("sentence_length:",sentence_length)
        print("WindowSize:",window_size)
        print("index:",index)
        print("Word at index {0} : '{1}'".format(index,word))
        
        context_words =[]
        context_words1 = []
       
        print("start = index - window_size")
        print("end = index + window_size + 1")
        
        start = index - window_size
        end = index + window_size + 1
        

        print("start:",start)
        print("end:",end)
       
        print("Choosing context word based on condition:")
        
        print([x for x in range(start, end)])
        for i in range(start, end):
            
            print("range index:",i)
            
            if 0 <= i:
                print("Statisfied the condition '0 <= i' ")
                
                if i < sentence_length:
                    print("Statisfied the condition 'i < sentence_length' ")
                    
                    if i != index:
                        print("Statisfied the condition 'i != index'")
                        print("Selected Word: '{0}'".format(words[i]))
            
            if  0 <= i < sentence_length and i != index:
                print("Word at range index at {0} is '{1}'".format(i,words[i]))
                context_words.append(words[i])
                
        
        print("Input:",context_words)   
        print("Output:",words[index])
        
        print("%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%")

    
        context_words1.append([words[i] for i in range(start, end) if 0 <= i < sentence_length and i != index])
        
        
        
        print("context_words :",context_words)
        print("context_words1 :",context_words1)
        print("*****************************")
    print("###############################################################################")

[5, 1, 6, 7, 2]
sentence_length: 5
WindowSize: 2
index: 0
Word at index 0 : '5'
start = index - window_size
end = index + window_size + 1
start: -2
end: 3
Choosing context word based on condition:
[-2, -1, 0, 1, 2]
range index: -2
range index: -1
range index: 0
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
range index: 1
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
Statisfied the condition 'i != index'
Selected Word: '1'
Word at range index at 1 is '1'
range index: 2
Statisfied the condition '0 <= i' 
Statisfied the condition 'i < sentence_length' 
Statisfied the condition 'i != index'
Selected Word: '6'
Word at range index at 2 is '6'
Input: [1, 6]
Output: 5
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
context_words : [1, 6]
context_words1 : [[1, 6]]
*****************************
sentence_length: 5
WindowSize: 2
index: 1
Word at index 1 : '1'
start = index - window_size
end =

In [62]:
from keras.preprocessing import sequence
from keras.utils import np_utils

window_size = 2

def generator():
    for words in wids:
        sentence_length = len(words)
        for index,word in enumerate(words):
            context_words =[]
            label_word = []

            start = index - window_size
            end = index + window_size + 1

            context_words.append([words[i] for i in range(start, end) if 0 <= i < sentence_length and i != index])

            label_word.append(word)
            
            x = sequence.pad_sequences(context_words, maxlen=7)
            y = np_utils.to_categorical(label_word, vocab_size)

            yield (x, y)

In [63]:
for x ,y in generator():
    print("input: {0}  output: {1}".format(x,y))

input: [[0 0 0 0 0 1 6]]  output: [[0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 5 6 7]]  output: [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 5 1 7 2]]  output: [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 1 6 2]]  output: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 0 6 7]]  output: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[0 0 0 0 0 8 9]]  output: [[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  0  2  9 10]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  2  8 10 11]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  8  9 11  3]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  9 10  3  4]]  output: [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]]
input: [[ 0  0  0 10 11  4 12]]  output: [[0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
input: [[ 0  0  0  

In [ ]:
# Skip Gram

In [64]:
from tensorflow.keras.preprocessing.sequence import skipgrams

# generate skip-grams
skip_grams = [skipgrams(wid, vocabulary_size=vocab_size, window_size=10) for wid in wids]

# view sample skip-grams
pairs, labels = skip_grams[0][0], skip_grams[0][1]
for i in range(10):
    print("({:s} ({:d}), {:s} ({:d})) -> {:d}".format(
          id2word[pairs[i][0]], pairs[i][0], 
          id2word[pairs[i][1]], pairs[i][1], 
          labels[i]))

(heaven (7), beginning (5)) -> 1
(heaven (7), created (6)) -> 1
(god (1), beginning (5)) -> 1
(heaven (7), earth (2)) -> 1
(beginning (5), heaven (7)) -> 1
(beginning (5), god (1)) -> 0
(beginning (5), void (10)) -> 0
(beginning (5), god (1)) -> 1
(beginning (5), earth (2)) -> 1
(god (1), created (6)) -> 1


In [65]:
from tensorflow.keras.preprocessing import text

tokenizer = text.Tokenizer()
tokenizer.fit_on_texts(norm_bible)

word2id = tokenizer.word_index
id2word = {v:k for k, v in word2id.items()}

vocab_size = len(word2id) + 1 
embed_size = 100

wids = [[word2id[w] for w in text.text_to_word_sequence(doc)] for doc in norm_bible]
print('Vocabulary Size:', vocab_size)
print('Vocabulary Sample:', list(word2id.items())[:10])

Vocabulary Size: 16
Vocabulary Sample: [('god', 1), ('earth', 2), ('upon', 3), ('face', 4), ('beginning', 5), ('created', 6), ('heaven', 7), ('without', 8), ('form', 9), ('void', 10)]


In [1]:
# Using Glove : Pretained Word Embedding

from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer

corpus = [
            'This is an excellent movie',
            'The move was fantastic I like it',
            'You should watch it is brilliant',
            'Exceptionally good',
            'Wonderfully directed and executed I like it',
            'Its a fantastic series',
            'Never watched such a brillent movie',
            'It is a Wonderful movie',
        ]

word_tokenizer = Tokenizer()
word_tokenizer.fit_on_texts(corpus)


Using TensorFlow backend.


In [2]:
vocab_length = len(word_tokenizer.word_index) + 1

print(vocab_length)

31


In [3]:
embedded_sentences = word_tokenizer.texts_to_sequences(corpus)

embedded_sentences

[[8, 2, 9, 10, 3],
 [11, 12, 13, 5, 6, 7, 1],
 [14, 15, 16, 1, 2, 17],
 [18, 19],
 [20, 21, 22, 23, 6, 7, 1],
 [24, 4, 5, 25],
 [26, 27, 28, 4, 29, 3],
 [1, 2, 4, 30, 3]]

In [4]:
from nltk.tokenize import word_tokenize
from keras.preprocessing.sequence import pad_sequences

word_count = lambda sentence: len(word_tokenize(sentence))
longest_sentence = max(corpus, key=word_count)
length_long_sentence = len(word_tokenize(longest_sentence))

padded_sentences = pad_sequences(embedded_sentences, length_long_sentence, padding='post')

print(padded_sentences)

[[ 8  2  9 10  3  0  0]
 [11 12 13  5  6  7  1]
 [14 15 16  1  2 17  0]
 [18 19  0  0  0  0  0]
 [20 21 22 23  6  7  1]
 [24  4  5 25  0  0  0]
 [26 27 28  4 29  3  0]
 [ 1  2  4 30  3  0  0]]


In [5]:
# Loading Pretrained Word Embeddings : Glove

# The smallest file is named "Glove.6B.zip". The size of the file is 822 MB. 
# The file contains 50, 100, 200, and 300 dimensional word vectors for 400k words. We will be using the 100 dimensional vector.

In [6]:
from numpy import array
from numpy import asarray
from numpy import zeros

In [7]:
# Empty dictionary that will store our word embeddings
embeddings_dictionary = dict()

# Loading the Pretrained Glove Word Embedding Model
glove_file = open('C:/MyWork/MyLearning/Career Growth/ML/Files/DataSet/glove.6B.100d.txt', encoding="utf8")

In [8]:
#  Here notice that we loaded glove.6B.100d.txt file. This file contains 100 dimensional word embeddings. 

# We will create a dictionary that will contain words as keys and the corresponding 100 dimensional vectors as values, 
#  in the form of an array.

for line in glove_file:
    records = line.split()
    word = records[0]
    vector_dimensions = asarray(records[1:], dtype='float32')
    embeddings_dictionary [word] = vector_dimensions
    
glove_file.close()

In [15]:
# The dictionary embeddings_dictionary now contains words and corresponding GloVe embeddings for all the words

embeddings_dictionary['the']

array([-0.038194, -0.24487 ,  0.72812 , -0.39961 ,  0.083172,  0.043953,
       -0.39141 ,  0.3344  , -0.57545 ,  0.087459,  0.28787 , -0.06731 ,
        0.30906 , -0.26384 , -0.13231 , -0.20757 ,  0.33395 , -0.33848 ,
       -0.31743 , -0.48336 ,  0.1464  , -0.37304 ,  0.34577 ,  0.052041,
        0.44946 , -0.46971 ,  0.02628 , -0.54155 , -0.15518 , -0.14107 ,
       -0.039722,  0.28277 ,  0.14393 ,  0.23464 , -0.31021 ,  0.086173,
        0.20397 ,  0.52624 ,  0.17164 , -0.082378, -0.71787 , -0.41531 ,
        0.20335 , -0.12763 ,  0.41367 ,  0.55187 ,  0.57908 , -0.33477 ,
       -0.36559 , -0.54857 , -0.062892,  0.26584 ,  0.30205 ,  0.99775 ,
       -0.80481 , -3.0243  ,  0.01254 , -0.36942 ,  2.2167  ,  0.72201 ,
       -0.24978 ,  0.92136 ,  0.034514,  0.46745 ,  1.1079  , -0.19358 ,
       -0.074575,  0.23353 , -0.052062, -0.22044 ,  0.057162, -0.15806 ,
       -0.30798 , -0.41625 ,  0.37972 ,  0.15006 , -0.53212 , -0.2055  ,
       -1.2526  ,  0.071624,  0.70565 ,  0.49744 , 

In [16]:
embeddings_dictionary['at']

array([ 0.1766   ,  0.093851 ,  0.24351  ,  0.44313  , -0.39037  ,
        0.12524  , -0.19918  ,  0.59855  , -0.82035  ,  0.28006  ,
        0.54231  ,  0.023079 ,  0.12837  , -0.044489 ,  0.3837   ,
       -0.75659  ,  0.40254  , -0.4462   , -0.81599  , -0.0091513,
        0.65219  , -0.043656 ,  0.54919  , -0.16696  ,  0.73028  ,
       -0.20703  , -0.069863 , -0.31259  ,  0.27226  ,  0.084905 ,
       -0.60498  ,  0.42826  ,  0.60134  ,  0.50953  , -0.39073  ,
        0.44608  , -0.36331  ,  0.50858  , -0.20308  , -0.43503  ,
       -0.086827 , -0.86581  , -1.0151   , -0.35725  , -0.12993  ,
        0.3324   ,  0.3026   ,  0.067277 , -0.52948  , -0.81223  ,
        0.39562  , -0.79537  ,  0.24331  ,  1.2506   , -1.0169   ,
       -3.3391   , -0.79691  , -0.33877  ,  1.366    ,  0.87513  ,
       -0.63701  ,  0.68381  , -0.057432 ,  0.12541  , -0.8258   ,
       -0.56117  ,  0.30807  ,  0.1545   ,  0.61473  ,  0.67403  ,
       -0.60833  , -0.25911  , -0.35619  , -0.71189  , -0.3120

In [17]:
# Creating word embedding for our Corpus

embedding_matrix = zeros((vocab_length, 100))

for word,index in word_tokenizer.word_index.items():
    print("word:{0} and index:{1}".format(word,index))
    print(embeddings_dictionary.get(word))
    
    embedding_vector = embeddings_dictionary.get(word)
    
    if embedding_vector is not None:
        embedding_matrix[index] = embedding_vector

word:it and index:1
[-3.0664e-01  1.6821e-01  9.8511e-01 -3.3606e-01 -2.4160e-01  1.6186e-01
 -5.3496e-02  4.3010e-01  5.7342e-01 -7.1569e-02  3.6101e-01  2.6729e-01
  2.7789e-01 -7.2268e-02  1.3838e-01 -2.6714e-01  1.2999e-01  2.2949e-01
 -1.8311e-01  5.0163e-01  4.4921e-01 -2.0821e-02  4.2642e-01 -6.8762e-02
  4.0337e-01  9.5198e-02 -3.1944e-01 -5.4651e-01 -1.3345e-01 -5.6511e-01
 -2.0975e-01  1.1592e+00 -1.9400e-01  1.9828e-01 -1.1924e-01  4.1781e-01
  6.8383e-03 -2.0537e-01 -5.3375e-01 -5.2225e-01 -3.8227e-01 -6.5833e-03
  1.4265e-01 -4.2502e-01 -3.1150e-01  2.7352e-03  7.5093e-01 -4.8218e-01
 -1.8595e-01 -7.7104e-01 -4.6406e-02 -6.9140e-02  4.1688e-01  1.3235e+00
 -8.1742e-01 -3.3998e+00 -1.1307e-01 -3.4123e-01  2.0775e+00  6.1369e-01
  1.4792e-01  9.3753e-01 -1.0138e-01  2.8426e-01  9.7899e-01 -3.2335e-01
  6.3697e-01  5.8308e-01  2.2820e-01 -3.1696e-01  2.1061e-01 -6.5060e-01
  2.1653e-01 -2.4347e-01  5.5519e-01 -3.4351e-01 -9.5093e-02 -1.4715e-01
 -1.2876e+00  3.9310e-01  3.016

In [20]:
embedding_matrix.shape

# 31 : My corpus Vocabulary
# 100 : Dimention of the word

(31, 100)

In [4]:
# Word2Vec Using gensim Model

from gensim.models import Word2Vec

norm_bible = ['beginning god created heaven earth',
             'earth without form void darkness upon face deep',
             'spirit god moved upon face waters']

norm_bible = [x.split() for x in norm_bible]

norm_bible

[['beginning', 'god', 'created', 'heaven', 'earth'],
 ['earth', 'without', 'form', 'void', 'darkness', 'upon', 'face', 'deep'],
 ['spirit', 'god', 'moved', 'upon', 'face', 'waters']]

In [5]:
# Vocabulary
_vocab = set([x for y in norm_bible for x in y])

_vocab

{'beginning',
 'created',
 'darkness',
 'deep',
 'earth',
 'face',
 'form',
 'god',
 'heaven',
 'moved',
 'spirit',
 'upon',
 'void',
 'waters',
 'without'}

In [6]:
# Vocab size
len(_vocab)

15

In [8]:
# Building the Word2Vec 

model = Word2Vec(sentences=norm_bible, max_vocab_size=100, window=5, min_count=1, workers=4)

In [9]:
# model.save("word2vec.model")
# model = Word2Vec.load("word2vec.model")

In [13]:
# If you save the model you can continue training it later:
model.train([["hello", "world"]], total_examples=1, epochs=1)

(0, 2)

In [14]:
model.wv.vocab

{'beginning': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9bc8>,
 'god': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9c88>,
 'created': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9cc8>,
 'heaven': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9d08>,
 'earth': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9dc8>,
 'without': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9d88>,
 'form': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9e08>,
 'void': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9e48>,
 'darkness': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9c48>,
 'upon': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9d48>,
 'face': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9e88>,
 'deep': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9ec8>,
 'spirit': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9f08>,
 'moved': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9f48>,
 'waters': <gensim.models.keyedvectors.Vocab at 0x19b2c8a9f88>}

In [16]:
# Bulding the vector : Numpy array for the word 

model.wv['god']  # get numpy vector of a word

array([-0.0049982 , -0.00495543,  0.00209568, -0.00377834, -0.0047039 ,
        0.00377543,  0.00446357,  0.00402102, -0.00120432,  0.00443419,
       -0.00336269, -0.00046212, -0.00294839,  0.00034047,  0.00109328,
        0.00097902, -0.00194222,  0.00453343,  0.00420529, -0.00413985,
       -0.00026492, -0.00105644, -0.00088214, -0.00387856, -0.00107633,
        0.00390099,  0.00364199, -0.00235461, -0.00188958, -0.00055888,
       -0.00179535, -0.00260311, -0.00431528, -0.00444491, -0.00311525,
       -0.00442708,  0.00059373, -0.00175032,  0.0004481 ,  0.00342633,
        0.00362875, -0.00408895,  0.00233011, -0.00074572,  0.00259224,
        0.00111378,  0.00019834, -0.0044388 ,  0.00204787, -0.00280272,
       -0.00190209, -0.00457306,  0.00271019, -0.00094671,  0.001092  ,
        0.00111628,  0.0043809 ,  0.00190675,  0.00205206,  0.00484966,
       -0.00032888, -0.00152577, -0.00419053,  0.00498315, -0.00337296,
        0.00291396, -0.00077983,  0.004306  ,  0.00166933,  0.00

In [17]:
model.wv['god','heaven']  # get numpy vector of a word

array([[-4.9981982e-03, -4.9554287e-03,  2.0956798e-03, -3.7783368e-03,
        -4.7039031e-03,  3.7754276e-03,  4.4635679e-03,  4.0210173e-03,
        -1.2043229e-03,  4.4341907e-03, -3.3626903e-03, -4.6211795e-04,
        -2.9483901e-03,  3.4047215e-04,  1.0932811e-03,  9.7901549e-04,
        -1.9422161e-03,  4.5334264e-03,  4.2052898e-03, -4.1398495e-03,
        -2.6492067e-04, -1.0564369e-03, -8.8213559e-04, -3.8785576e-03,
        -1.0763302e-03,  3.9009862e-03,  3.6419891e-03, -2.3546142e-03,
        -1.8895830e-03, -5.5888243e-04, -1.7953550e-03, -2.6031071e-03,
        -4.3152752e-03, -4.4449074e-03, -3.1152535e-03, -4.4270777e-03,
         5.9372769e-04, -1.7503235e-03,  4.4810280e-04,  3.4263306e-03,
         3.6287452e-03, -4.0889466e-03,  2.3301095e-03, -7.4572384e-04,
         2.5922395e-03,  1.1137846e-03,  1.9833964e-04, -4.4387956e-03,
         2.0478657e-03, -2.8027203e-03, -1.9020891e-03, -4.5730560e-03,
         2.7101890e-03, -9.4670954e-04,  1.0919985e-03,  1.11627

In [20]:
# get other similar words

sims = model.wv.most_similar('god', topn=10)  

sims

[('moved', 0.14142993092536926),
 ('darkness', 0.13165391981601715),
 ('spirit', 0.1094588041305542),
 ('without', 0.09498775750398636),
 ('form', 0.03891271352767944),
 ('beginning', 0.01158369705080986),
 ('earth', -0.044981859624385834),
 ('face', -0.06618501245975494),
 ('void', -0.0918918028473854),
 ('deep', -0.10328714549541473)]

In [ ]:
# Difference between Word2Vec and Doc2Vec
# 1. As the names suggest Word2Vec is trained on single words while Doc2vec is trained texts of variable length,

# Glove and word2vec, these are unsupervised approaches for building vectors from text data.
# The main difference is the functioning of both models. Glove is Count based model, and Word2vec is predictive modeling
