In [1]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
count = CountVectorizer()

docs = np.array(['The sun is shining','The weather is sweet','The sun is shining and the weather is sweet'])

In [3]:
bag = count.fit_transform(docs)

In [4]:
print(count.vocabulary_)

{'the': 5, 'sun': 3, 'is': 1, 'shining': 2, 'weather': 6, 'sweet': 4, 'and': 0}


In [20]:
print(bag.toarray())

[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [22]:
# and = 0
# is =1
# shining = 2
# sun =3
# sweet =4
# the =5
# wether =6

In [ ]:
# Observe the first sentence if the word Exist on Above Voculary its 1 else 0

# 'The sun is shining'
# 0 1 1 1 0 1 0