In [11]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

ocs = np.array(['The sun is shining','The weather is sweet','The sun is shining and the weather is sweet'])

count = CountVectorizer()


docs = np.array(['The sun is shining','The weather is sweet','The sun is shining and the weather is sweet'])

bag = count.fit_transform(docs)

print(count.vocabulary_)

{'the': 5, 'sun': 3, 'is': 1, 'shining': 2, 'weather': 6, 'sweet': 4, 'and': 0}


In [12]:
print(bag.toarray())

[[0 1 1 1 0 1 0]
 [0 1 0 0 1 1 1]
 [1 2 1 1 1 2 1]]


In [24]:
# tf-idf = tf(i,d) * idf(t,d)

# td(i,d) = term frequency

# idf(t,d) = 	log(n/1+df(t,d)) :  inverse document frequency  df(t,d) : no. of documents d that contain the term t

tfidf = TfidfTransformer()

np.set_printoptions(precision=2)

print(tfidf.fit_transform(count.fit_transform(docs)).toarray())

[[0.   0.43 0.56 0.56 0.   0.43 0.  ]
 [0.   0.43 0.   0.   0.56 0.43 0.56]
 [0.4  0.48 0.31 0.31 0.31 0.48 0.31]]
