In [17]:
# Example 1 : using Keras

import numpy as np
from tensorflow.keras.preprocessing import sequence

data_vec = [['3', '18', '9', '3', '11', '5', '20'],
            ['3', '8', '1', '12'],
            ['18', '1', '8', '1'],
            ['8', '1', '9', '14'],
            ['25', '1', '8', '1'],
            ['9']]

maxl=np.max([len(x) for x in data_vec])

print('maxl:{0}'.format(maxl))

x_data_vec = sequence.pad_sequences(data_vec, maxlen=maxl)

x_data_vec

maxl:7


array([[ 3, 18,  9,  3, 11,  5, 20],
       [ 0,  0,  0,  3,  8,  1, 12],
       [ 0,  0,  0, 18,  1,  8,  1],
       [ 0,  0,  0,  8,  1,  9, 14],
       [ 0,  0,  0, 25,  1,  8,  1],
       [ 0,  0,  0,  0,  0,  0,  9]])

In [18]:
# padding = 'post'

x_data_vec = sequence.pad_sequences(data_vec, maxlen=maxl,padding='post')

x_data_vec

array([[ 3, 18,  9,  3, 11,  5, 20],
       [ 3,  8,  1, 12,  0,  0,  0],
       [18,  1,  8,  1,  0,  0,  0],
       [ 8,  1,  9, 14,  0,  0,  0],
       [25,  1,  8,  1,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0,  0]])

In [19]:
# Max Length

x_data_vec = sequence.pad_sequences(data_vec, maxlen=10,padding='post')

x_data_vec

array([[ 3, 18,  9,  3, 11,  5, 20,  0,  0,  0],
       [ 3,  8,  1, 12,  0,  0,  0,  0,  0,  0],
       [18,  1,  8,  1,  0,  0,  0,  0,  0,  0],
       [ 8,  1,  9, 14,  0,  0,  0,  0,  0,  0],
       [25,  1,  8,  1,  0,  0,  0,  0,  0,  0],
       [ 9,  0,  0,  0,  0,  0,  0,  0,  0,  0]])