In [1]:
# Example 2:

import numpy as np

data = [['Thanks', 'for', 'an', 'excellent', 'report'],
        ['Your', 'service', 'is', 'very', 'quick', 'and', 'fast'],
        ['I', 'am', 'pleased', 'with', 'your', 'service']]

wrds = []

[[wrds.append(w.lower()) for w in x] for x in data]

wrds = set(wrds)

print(wrds,"\n")

word_id = {}

for i,w in enumerate(wrds,1):
    word_id[w] = i
    
print(word_id,"\n")

row = len(data)

column = np.max([len(x) for x in data])

print("row={0} and column={1}".format(row,column))

seq_embedding = np.zeros((row,column))

print("seq_embedding = \n {0}".format(seq_embedding))

print("\n")

for i in range(len(data)):
    doc = data[i]
    for j in range(len(doc)):
        id = word_id[(doc[j]).lower()]
        seq_embedding[i][j] = id
        
print(seq_embedding)

{'i', 'fast', 'pleased', 'excellent', 'for', 'is', 'very', 'and', 'your', 'am', 'report', 'thanks', 'quick', 'service', 'an', 'with'} 

{'i': 1, 'fast': 2, 'pleased': 3, 'excellent': 4, 'for': 5, 'is': 6, 'very': 7, 'and': 8, 'your': 9, 'am': 10, 'report': 11, 'thanks': 12, 'quick': 13, 'service': 14, 'an': 15, 'with': 16} 

row=3 and column=7
seq_embedding = 
 [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


[[12.  5. 15.  4. 11.  0.  0.]
 [ 9. 14.  6.  7. 13.  8.  2.]
 [ 1. 10.  3. 16.  9. 14.  0.]]
